//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyMonitor.DummyServiceClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudyTaskService", Namespace="http://schemas.datacontract.org/2004/07/StudyMonitor.Service")]
    [System.SerializableAttribute()]
    public partial class StudyTaskService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskTimeSpanService", Namespace="http://schemas.datacontract.org/2004/07/StudyMonitor.Service")]
    [System.SerializableAttribute()]
    public partial class TaskTimeSpanService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService TaskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IStudyTasksService")]
    public interface IStudyTasksService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/Add", ReplyAction="http://tempuri.org/IStudyTasksService/AddResponse")]
        int Add(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/Add", ReplyAction="http://tempuri.org/IStudyTasksService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/GetTask", ReplyAction="http://tempuri.org/IStudyTasksService/GetTaskResponse")]
        StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService GetTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/GetTask", ReplyAction="http://tempuri.org/IStudyTasksService/GetTaskResponse")]
        System.Threading.Tasks.Task<StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService> GetTaskAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/AddTimeSpanTo", ReplyAction="http://tempuri.org/IStudyTasksService/AddTimeSpanToResponse")]
        void AddTimeSpanTo(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task, StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService timeSpan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/AddTimeSpanTo", ReplyAction="http://tempuri.org/IStudyTasksService/AddTimeSpanToResponse")]
        System.Threading.Tasks.Task AddTimeSpanToAsync(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task, StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService timeSpan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/GetTimeSpansFor", ReplyAction="http://tempuri.org/IStudyTasksService/GetTimeSpansForResponse")]
        StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService[] GetTimeSpansFor(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudyTasksService/GetTimeSpansFor", ReplyAction="http://tempuri.org/IStudyTasksService/GetTimeSpansForResponse")]
        System.Threading.Tasks.Task<StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService[]> GetTimeSpansForAsync(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudyTasksServiceChannel : StudyMonitor.DummyServiceClient.ServiceReference.IStudyTasksService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudyTasksServiceClient : System.ServiceModel.ClientBase<StudyMonitor.DummyServiceClient.ServiceReference.IStudyTasksService>, StudyMonitor.DummyServiceClient.ServiceReference.IStudyTasksService {
        
        public StudyTasksServiceClient() {
        }
        
        public StudyTasksServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudyTasksServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudyTasksServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudyTasksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task) {
            return base.Channel.Add(task);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task) {
            return base.Channel.AddAsync(task);
        }
        
        public StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService GetTask(int id) {
            return base.Channel.GetTask(id);
        }
        
        public System.Threading.Tasks.Task<StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService> GetTaskAsync(int id) {
            return base.Channel.GetTaskAsync(id);
        }
        
        public void AddTimeSpanTo(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task, StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService timeSpan) {
            base.Channel.AddTimeSpanTo(task, timeSpan);
        }
        
        public System.Threading.Tasks.Task AddTimeSpanToAsync(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task, StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService timeSpan) {
            return base.Channel.AddTimeSpanToAsync(task, timeSpan);
        }
        
        public StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService[] GetTimeSpansFor(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task) {
            return base.Channel.GetTimeSpansFor(task);
        }
        
        public System.Threading.Tasks.Task<StudyMonitor.DummyServiceClient.ServiceReference.TaskTimeSpanService[]> GetTimeSpansForAsync(StudyMonitor.DummyServiceClient.ServiceReference.StudyTaskService task) {
            return base.Channel.GetTimeSpansForAsync(task);
        }
    }
}
